marker_groups = {
    "normalrender": [
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Signs",
            "groupName": "G_Sign",
            "icon": "signpost_icon.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Chests",
            "groupName": "G_Chest",
            "icon": "markers/chest.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Trapped Chests",
            "groupName": "G_Trapped_Chest",
            "icon": "markers/chest_red.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Barrels",
            "groupName": "G_Barrel",
            "icon": "markers/barrel.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Item Frames",
            "groupName": "G_Item_Frame",
            "icon": "markers/item_frame.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Armor Stands",
            "groupName": "G_Armor_Stand",
            "icon": "markers/armor_stand.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Lectern",
            "groupName": "G_Lectern",
            "icon": "markers/lectern.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Special Villagers",
            "groupName": "G_Villager",
            "icon": "markers/villager.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Books",
            "groupName": "G_Book",
            "icon": "markers/book.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Maps",
            "groupName": "G_Map",
            "icon": "markers/map.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Enchanted Books",
            "groupName": "G_Enchanted_Book",
            "icon": "markers/enchanted_book.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Town # broken",
            "groupName": "G_Town",
            "icon": "markers/marker_town.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Tower # broken",
            "groupName": "G_Tower",
            "icon": "markers/marker_tower_red.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Spawner",
            "groupName": "G_Spawner",
            "icon": "markers/spawner.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Pig",
            "groupName": "G_Pig",
            "icon": "markers/pig.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Sheep",
            "groupName": "G_Sheep",
            "icon": "markers/sheep.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Cow",
            "groupName": "G_Cow",
            "icon": "markers/cow.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Chicken",
            "groupName": "G_Chicken",
            "icon": "markers/chicken.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Mooshroom",
            "groupName": "G_Mooshroom",
            "icon": "markers/mooshroom.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Wolf",
            "groupName": "G_Wolf",
            "icon": "markers/wolf.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Ocelot",
            "groupName": "G_Ocelot",
            "icon": "markers/ocelot.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Cat",
            "groupName": "G_Cat",
            "icon": "markers/cat.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Horse",
            "groupName": "G_Horse",
            "icon": "markers/horse.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": True,
            "displayName": "Donkey",
            "groupName": "G_Donkey",
            "icon": "markers/donkey.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Elder Guardian",
            "groupName": "G_Elder_Guardian",
            "icon": "markers/elder_guardian.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Llama",
            "groupName": "G_Llama",
            "icon": "markers/llama.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Rabbit",
            "groupName": "G_Rabbit",
            "icon": "markers/rabbit.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Panda",
            "groupName": "G_Panda",
            "icon": "markers/panda.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Polar Bear",
            "groupName": "G_Polar_Bear",
            "icon": "markers/polar_bear.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Turtle",
            "groupName": "G_Turtle",
            "icon": "markers/turtle.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Parrot",
            "groupName": "G_Parrot",
            "icon": "markers/parrot.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Fox",
            "groupName": "G_Fox",
            "icon": "markers/fox.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Drowned",
            "groupName": "G_Drowned",
            "icon": "markers/drowned.png",
            "showIconInLegend": True,
        },
        {
            "checked": False,
            "createInfoWindow": False,
            "displayName": "Bee",
            "groupName": "G_Bee",
            "icon": "markers/bee.png",
            "showIconInLegend": True,
        },
    ]
}
