ALL_ITEMS = {
    "minecraft:acacia_boat": "Acacia Boat",
    "minecraft:acacia_button": "Acacia Button",
    "minecraft:acacia_chest_boat": "Acacia Boat with Chest",
    "minecraft:acacia_door": "Acacia Door",
    "minecraft:acacia_fence": "Acacia Fence",
    "minecraft:acacia_fence_gate": "Acacia Fence Gate",
    "minecraft:acacia_hanging_sign": "Acacia Hanging Sign",
    "minecraft:acacia_leaves": "Acacia Leaves",
    "minecraft:acacia_log": "Acacia Log",
    "minecraft:acacia_planks": "Acacia Planks",
    "minecraft:acacia_pressure_plate": "Acacia Pressure Plate",
    "minecraft:acacia_sapling": "Acacia Sapling",
    "minecraft:acacia_sign": "Acacia Sign",
    "minecraft:acacia_slab": "Acacia Slab",
    "minecraft:acacia_stairs": "Acacia Stairs",
    "minecraft:acacia_trapdoor": "Acacia Trapdoor",
    "minecraft:acacia_wood": "Acacia Wood",
    "minecraft:activator_rail": "Activator Rail",
    "minecraft:air": "",
    "minecraft:allay_spawn_egg": "Allay Spawn Egg",
    "minecraft:allium": "Allium",
    "minecraft:amethyst_block": "Block of Amethyst",
    "minecraft:amethyst_cluster": "Amethyst Cluster",
    "minecraft:amethyst_shard": "Amethyst Shard",
    "minecraft:ancient_debris": "Celestial Debris",
    "minecraft:andesite": "Andesite",
    "minecraft:andesite_slab": "Andesite Slab",
    "minecraft:andesite_stairs": "Andesite Stairs",
    "minecraft:andesite_wall": "Andesite Wall",
    "minecraft:angler_pottery_sherd": "Angler Pottery Sherd",
    "minecraft:anvil": "Anvil",
    "minecraft:apple": "Apple",
    "minecraft:archer_pottery_sherd": "Archer Pottery Sherd",
    "minecraft:armor_stand": "Armor Stand",
    "minecraft:arms_up_pottery_sherd": "Arms Up Pottery Sherd",
    "minecraft:arrow": "Arrow",
    "minecraft:axolotl_bucket": "Bucket of Axolotl",
    "minecraft:axolotl_spawn_egg": "Axolotl Spawn Egg",
    "minecraft:azalea": "Azalea",
    "minecraft:azalea_leaves": "Azalea Leaves",
    "minecraft:azure_bluet": "Azure Bluet",
    "minecraft:baked_potato": "Baked Potato",
    "minecraft:bamboo": "Bamboo",
    "minecraft:bamboo_block": "Block of Bamboo",
    "minecraft:bamboo_button": "Bamboo Button",
    "minecraft:bamboo_chest_raft": "Bamboo Raft with Chest",
    "minecraft:bamboo_door": "Bamboo Door",
    "minecraft:bamboo_fence": "Bamboo Fence",
    "minecraft:bamboo_fence_gate": "Bamboo Fence Gate",
    "minecraft:bamboo_hanging_sign": "Bamboo Hanging Sign",
    "minecraft:bamboo_mosaic": "Bamboo Mosaic",
    "minecraft:bamboo_mosaic_slab": "Bamboo Mosaic Slab",
    "minecraft:bamboo_mosaic_stairs": "Bamboo Mosaic Stairs",
    "minecraft:bamboo_planks": "Bamboo Planks",
    "minecraft:bamboo_pressure_plate": "Bamboo Pressure Plate",
    "minecraft:bamboo_raft": "Bamboo Raft",
    "minecraft:bamboo_sign": "Bamboo Sign",
    "minecraft:bamboo_slab": "Bamboo Slab",
    "minecraft:bamboo_stairs": "Bamboo Stairs",
    "minecraft:bamboo_trapdoor": "Bamboo Trapdoor",
    "minecraft:barrel": "Barrel",
    "minecraft:barrier": "Barrier",
    "minecraft:basalt": "Basalt",
    "minecraft:bat_spawn_egg": "Masayoshi",
    "minecraft:beacon": "Asterial Array",
    "minecraft:bedrock": "Condensed Veilstone",
    "minecraft:bee_nest": "Bee Nest",
    "minecraft:bee_spawn_egg": "Peace Treaty",
    "minecraft:beef": "Raw Beef",
    "minecraft:beehive": "Beehive",
    "minecraft:beetroot": "Beetroot",
    "minecraft:beetroot_seeds": "Beetroot Seeds",
    "minecraft:beetroot_soup": "Beetroot Soup",
    "minecraft:bell": "Bell",
    "minecraft:big_dripleaf": "Big Dripleaf",
    "minecraft:birch_boat": "Birch Boat",
    "minecraft:birch_button": "Birch Button",
    "minecraft:birch_chest_boat": "Birch Boat with Chest",
    "minecraft:birch_door": "Birch Door",
    "minecraft:birch_fence": "Birch Fence",
    "minecraft:birch_fence_gate": "Birch Fence Gate",
    "minecraft:birch_hanging_sign": "Birch Hanging Sign",
    "minecraft:birch_leaves": "Birch Leaves",
    "minecraft:birch_log": "Birch Log",
    "minecraft:birch_planks": "Birch Planks",
    "minecraft:birch_pressure_plate": "Birch Pressure Plate",
    "minecraft:birch_sapling": "Birch Sapling",
    "minecraft:birch_sign": "Birch Sign",
    "minecraft:birch_slab": "Birch Slab",
    "minecraft:birch_stairs": "Birch Stairs",
    "minecraft:birch_trapdoor": "Birch Trapdoor",
    "minecraft:birch_wood": "Birch Wood",
    "minecraft:black_banner": "Black Banner",
    "minecraft:black_bed": "Black Bed",
    "minecraft:black_candle": "Black Candle",
    "minecraft:black_carpet": "Black Carpet",
    "minecraft:black_concrete": "Black Concrete",
    "minecraft:black_concrete_powder": "Black Concrete Powder",
    "minecraft:black_dye": "Black Dye",
    "minecraft:black_glazed_terracotta": "Black Glazed Terracotta",
    "minecraft:black_shulker_box": "Black Runic Vessel",
    "minecraft:black_stained_glass": "Black Stained Glass",
    "minecraft:black_stained_glass_pane": "Black Stained Glass Pane",
    "minecraft:black_terracotta": "Black Terracotta",
    "minecraft:black_wool": "Black Wool",
    "minecraft:blackstone": "Blackstone",
    "minecraft:blackstone_slab": "Blackstone Slab",
    "minecraft:blackstone_stairs": "Blackstone Stairs",
    "minecraft:blackstone_wall": "Blackstone Wall",
    "minecraft:blade_pottery_sherd": "Blade Pottery Sherd",
    "minecraft:blast_furnace": "Blast Furnace",
    "minecraft:blaze_powder": "Blaze Powder",
    "minecraft:blaze_rod": "Blaze Rod",
    "minecraft:blaze_spawn_egg": "Inert Mythbreaker",
    "minecraft:blue_banner": "Blue Banner",
    "minecraft:blue_bed": "Blue Bed",
    "minecraft:blue_candle": "Blue Candle",
    "minecraft:blue_carpet": "Blue Carpet",
    "minecraft:blue_concrete": "Blue Concrete",
    "minecraft:blue_concrete_powder": "Blue Concrete Powder",
    "minecraft:blue_dye": "Blue Dye",
    "minecraft:blue_glazed_terracotta": "Blue Glazed Terracotta",
    "minecraft:blue_ice": "Divine Ice",
    "minecraft:blue_orchid": "Blue Orchid",
    "minecraft:blue_shulker_box": "Blue Runic Vessel",
    "minecraft:blue_stained_glass": "Blue Stained Glass",
    "minecraft:blue_stained_glass_pane": "Blue Stained Glass Pane",
    "minecraft:blue_terracotta": "Blue Terracotta",
    "minecraft:blue_wool": "Blue Wool",
    "minecraft:bone": "Bone",
    "minecraft:bone_block": "Bone Block",
    "minecraft:bone_meal": "Bone Meal",
    "minecraft:book": "Book",
    "minecraft:bookshelf": "Bookshelf",
    "minecraft:bow": "Bow",
    "minecraft:bowl": "Bowl",
    "minecraft:brain_coral": "Brain Coral",
    "minecraft:brain_coral_block": "Brain Coral Block",
    "minecraft:brain_coral_fan": "Brain Coral Fan",
    "minecraft:bread": "Bread",
    "minecraft:brewer_pottery_sherd": "Brewer Pottery Sherd",
    "minecraft:brewing_stand": "Brewing Stand",
    "minecraft:brick": "Brick",
    "minecraft:brick_slab": "Brick Slab",
    "minecraft:brick_stairs": "Brick Stairs",
    "minecraft:brick_wall": "Brick Wall",
    "minecraft:bricks": "Bricks",
    "minecraft:brown_banner": "Brown Banner",
    "minecraft:brown_bed": "Brown Bed",
    "minecraft:brown_candle": "Brown Candle",
    "minecraft:brown_carpet": "Brown Carpet",
    "minecraft:brown_concrete": "Brown Concrete",
    "minecraft:brown_concrete_powder": "Brown Concrete Powder",
    "minecraft:brown_dye": "Brown Dye",
    "minecraft:brown_glazed_terracotta": "Brown Glazed Terracotta",
    "minecraft:brown_mushroom": "Brown Mushroom",
    "minecraft:brown_mushroom_block": "Brown Mushroom Block",
    "minecraft:brown_shulker_box": "Brown Runic Vessel",
    "minecraft:brown_stained_glass": "Brown Stained Glass",
    "minecraft:brown_stained_glass_pane": "Brown Stained Glass Pane",
    "minecraft:brown_terracotta": "Brown Terracotta",
    "minecraft:brown_wool": "Brown Wool",
    "minecraft:brush": "Brush",
    "minecraft:bubble_coral": "Bubble Coral",
    "minecraft:bubble_coral_block": "Bubble Coral Block",
    "minecraft:bubble_coral_fan": "Bubble Coral Fan",
    "minecraft:bucket": "Bucket",
    "minecraft:budding_amethyst": "Budding Amethyst",
    "minecraft:bundle": "Bundle",
    "minecraft:burn_pottery_sherd": "Burn Pottery Sherd",
    "minecraft:cactus": "Cactus",
    "minecraft:cake": "Cake",
    "minecraft:calcite": "Calcite",
    "minecraft:calibrated_sculk_sensor": "Calibrated Sculk Sensor",
    "minecraft:camel_spawn_egg": "Camel Spawn Egg",
    "minecraft:campfire": "Campfire",
    "minecraft:candle": "Candle",
    "minecraft:carrot": "Carrot",
    "minecraft:carrot_on_a_stick": "Carrot on a Stick",
    "minecraft:cartography_table": "Cartography Table",
    "minecraft:carved_pumpkin": "Carved Pumpkin",
    "minecraft:cat_spawn_egg": "Crystal Digging Claws",
    "minecraft:cauldron": "Cauldron",
    "minecraft:cave_spider_spawn_egg": "Cave Spider Spawn Egg",
    "minecraft:chain": "Chain",
    "minecraft:chain_command_block": "Chain Command Block",
    "minecraft:chainmail_boots": "Chainmail Boots",
    "minecraft:chainmail_chestplate": "Chainmail Chestplate",
    "minecraft:chainmail_helmet": "Chainmail Helmet",
    "minecraft:chainmail_leggings": "Chainmail Leggings",
    "minecraft:charcoal": "Charcoal",
    "minecraft:cherry_boat": "Cherry Boat",
    "minecraft:cherry_button": "Cherry Button",
    "minecraft:cherry_chest_boat": "Cherry Boat with Chest",
    "minecraft:cherry_door": "Cherry Door",
    "minecraft:cherry_fence": "Cherry Fence",
    "minecraft:cherry_fence_gate": "Cherry Fence Gate",
    "minecraft:cherry_hanging_sign": "Cherry Hanging Sign",
    "minecraft:cherry_leaves": "Cherry Leaves",
    "minecraft:cherry_log": "Cherry Log",
    "minecraft:cherry_planks": "Cherry Planks",
    "minecraft:cherry_pressure_plate": "Cherry Pressure Plate",
    "minecraft:cherry_sapling": "Cherry Sapling",
    "minecraft:cherry_sign": "Cherry Sign",
    "minecraft:cherry_slab": "Cherry Slab",
    "minecraft:cherry_stairs": "Cherry Stairs",
    "minecraft:cherry_trapdoor": "Cherry Trapdoor",
    "minecraft:cherry_wood": "Cherry Wood",
    "minecraft:chest": "Chest",
    "minecraft:chest_minecart": "Minecart with Chest",
    "minecraft:chicken": "Raw Chicken",
    "minecraft:chicken_spawn_egg": "Flammer",
    "minecraft:chipped_anvil": "Chipped Anvil",
    "minecraft:chiseled_bookshelf": "Chiseled Bookshelf",
    "minecraft:chiseled_deepslate": "Chiseled Slate",
    "minecraft:chiseled_nether_bricks": "Chiseled Taihryte Bricks",
    "minecraft:chiseled_polished_blackstone": "Chiseled Polished Blackstone",
    "minecraft:chiseled_quartz_block": "Chiseled Quartz Block",
    "minecraft:chiseled_red_sandstone": "Chiseled Red Sandstone",
    "minecraft:chiseled_sandstone": "Chiseled Sandstone",
    "minecraft:chiseled_stone_bricks": "Chiseled Stone Bricks",
    "minecraft:chorus_flower": "Chorus Flower",
    "minecraft:chorus_fruit": "Chorus Fruit",
    "minecraft:chorus_plant": "Chorus Plant",
    "minecraft:clay": "Clay",
    "minecraft:clay_ball": "Clay Ball",
    "minecraft:clock": "Clock",
    "minecraft:coal": "Coal",
    "minecraft:coal_block": "Block of Coal",
    "minecraft:coal_ore": "Coal Ore",
    "minecraft:coarse_dirt": "Coarse Dirt",
    "minecraft:coast_armor_trim_smithing_template": "Smithing Template",
    "minecraft:cobbled_deepslate": "Cobbled Slate",
    "minecraft:cobbled_deepslate_slab": "Cobbled Slate Slab",
    "minecraft:cobbled_deepslate_stairs": "Cobbled Slate Stairs",
    "minecraft:cobbled_deepslate_wall": "Cobbled Slate Wall",
    "minecraft:cobblestone": "Cobblestone",
    "minecraft:cobblestone_slab": "Cobblestone Slab",
    "minecraft:cobblestone_stairs": "Cobblestone Stairs",
    "minecraft:cobblestone_wall": "Cobblestone Wall",
    "minecraft:cobweb": "Cobweb",
    "minecraft:cocoa_beans": "Cocoa Beans",
    "minecraft:cod": "Raw Cod",
    "minecraft:cod_bucket": "Bucket of Cod",
    "minecraft:cod_spawn_egg": "Syzygy",
    "minecraft:command_block": "Command Block",
    "minecraft:command_block_minecart": "Minecart with Command Block",
    "minecraft:comparator": "Redstone Comparator",
    "minecraft:compass": "Compass",
    "minecraft:composter": "Composter",
    "minecraft:conduit": "Aqua Fortis",
    "minecraft:cooked_beef": "Steak",
    "minecraft:cooked_chicken": "Cooked Chicken",
    "minecraft:cooked_cod": "Cooked Cod",
    "minecraft:cooked_mutton": "Cooked Mutton",
    "minecraft:cooked_porkchop": "Cooked Porkchop",
    "minecraft:cooked_rabbit": "Cooked Rabbit",
    "minecraft:cooked_salmon": "Cooked Salmon",
    "minecraft:cookie": "Cookie",
    "minecraft:copper_block": "Block of Copper",
    "minecraft:copper_ingot": "Copper Ingot",
    "minecraft:copper_ore": "Copper Ore",
    "minecraft:cornflower": "Cornflower",
    "minecraft:cow_spawn_egg": "Calamity",
    "minecraft:cracked_deepslate_bricks": "Cracked Slate Bricks",
    "minecraft:cracked_deepslate_tiles": "Cracked Slate Tiles",
    "minecraft:cracked_nether_bricks": "Cracked Taihryte Bricks",
    "minecraft:cracked_polished_blackstone_bricks": "Cracked Polished Blackstone Bricks",
    "minecraft:cracked_stone_bricks": "Cracked Stone Bricks",
    "minecraft:crafting_table": "Crafting Table",
    "minecraft:creeper_banner_pattern": "Banner Pattern",
    "minecraft:creeper_head": "Creeper Head",
    "minecraft:creeper_spawn_egg": "Parenchyma",
    "minecraft:crimson_button": "Carnelian Button",
    "minecraft:crimson_door": "Carnelian Door",
    "minecraft:crimson_fence": "Carnelian Fence",
    "minecraft:crimson_fence_gate": "Carnelian Fence Gate",
    "minecraft:crimson_fungus": "Carnelian Fungus",
    "minecraft:crimson_hanging_sign": "Carnelian Hanging Sign",
    "minecraft:crimson_hyphae": "Carnelian Hyphae",
    "minecraft:crimson_nylium": "Carnelian Nylium",
    "minecraft:crimson_planks": "Carnelian Planks",
    "minecraft:crimson_pressure_plate": "Carnelian Pressure Plate",
    "minecraft:crimson_roots": "Carnelian Roots",
    "minecraft:crimson_sign": "Carnelian Sign",
    "minecraft:crimson_slab": "Carnelian Slab",
    "minecraft:crimson_stairs": "Carnelian Stairs",
    "minecraft:crimson_stem": "Carnelian Stem",
    "minecraft:crimson_trapdoor": "Carnelian Trapdoor",
    "minecraft:crossbow": "Crossbow",
    "minecraft:crying_obsidian": "Silent Obsidian",
    "minecraft:cut_copper": "Cut Copper",
    "minecraft:cut_copper_slab": "Cut Copper Slab",
    "minecraft:cut_copper_stairs": "Cut Copper Stairs",
    "minecraft:cut_red_sandstone": "Cut Red Sandstone",
    "minecraft:cut_red_sandstone_slab": "Cut Red Sandstone Slab",
    "minecraft:cut_sandstone": "Cut Sandstone",
    "minecraft:cut_sandstone_slab": "Cut Sandstone Slab",
    "minecraft:cyan_banner": "Cyan Banner",
    "minecraft:cyan_bed": "Cyan Bed",
    "minecraft:cyan_candle": "Cyan Candle",
    "minecraft:cyan_carpet": "Cyan Carpet",
    "minecraft:cyan_concrete": "Cyan Concrete",
    "minecraft:cyan_concrete_powder": "Cyan Concrete Powder",
    "minecraft:cyan_dye": "Cyan Dye",
    "minecraft:cyan_glazed_terracotta": "Cyan Glazed Terracotta",
    "minecraft:cyan_shulker_box": "Cyan Runic Vessel",
    "minecraft:cyan_stained_glass": "Cyan Stained Glass",
    "minecraft:cyan_stained_glass_pane": "Cyan Stained Glass Pane",
    "minecraft:cyan_terracotta": "Cyan Terracotta",
    "minecraft:cyan_wool": "Cyan Wool",
    "minecraft:damaged_anvil": "Damaged Anvil",
    "minecraft:dandelion": "Dandelion",
    "minecraft:danger_pottery_sherd": "Danger Pottery Sherd",
    "minecraft:dark_oak_boat": "Dark Oak Boat",
    "minecraft:dark_oak_button": "Dark Oak Button",
    "minecraft:dark_oak_chest_boat": "Dark Oak Boat with Chest",
    "minecraft:dark_oak_door": "Dark Oak Door",
    "minecraft:dark_oak_fence": "Dark Oak Fence",
    "minecraft:dark_oak_fence_gate": "Dark Oak Fence Gate",
    "minecraft:dark_oak_hanging_sign": "Dark Oak Hanging Sign",
    "minecraft:dark_oak_leaves": "Dark Oak Leaves",
    "minecraft:dark_oak_log": "Dark Oak Log",
    "minecraft:dark_oak_planks": "Dark Oak Planks",
    "minecraft:dark_oak_pressure_plate": "Dark Oak Pressure Plate",
    "minecraft:dark_oak_sapling": "Dark Oak Sapling",
    "minecraft:dark_oak_sign": "Dark Oak Sign",
    "minecraft:dark_oak_slab": "Dark Oak Slab",
    "minecraft:dark_oak_stairs": "Dark Oak Stairs",
    "minecraft:dark_oak_trapdoor": "Dark Oak Trapdoor",
    "minecraft:dark_oak_wood": "Dark Oak Wood",
    "minecraft:dark_prismarine": "Dark Prismarine",
    "minecraft:dark_prismarine_slab": "Dark Prismarine Slab",
    "minecraft:dark_prismarine_stairs": "Dark Prismarine Stairs",
    "minecraft:daylight_detector": "Daylight Detector",
    "minecraft:dead_brain_coral": "Dead Brain Coral",
    "minecraft:dead_brain_coral_block": "Dead Brain Coral Block",
    "minecraft:dead_brain_coral_fan": "Dead Brain Coral Fan",
    "minecraft:dead_bubble_coral": "Dead Bubble Coral",
    "minecraft:dead_bubble_coral_block": "Dead Bubble Coral Block",
    "minecraft:dead_bubble_coral_fan": "Dead Bubble Coral Fan",
    "minecraft:dead_bush": "Dead Bush",
    "minecraft:dead_fire_coral": "Dead Fire Coral",
    "minecraft:dead_fire_coral_block": "Dead Fire Coral Block",
    "minecraft:dead_fire_coral_fan": "Dead Fire Coral Fan",
    "minecraft:dead_horn_coral": "Dead Horn Coral",
    "minecraft:dead_horn_coral_block": "Dead Horn Coral Block",
    "minecraft:dead_horn_coral_fan": "Dead Horn Coral Fan",
    "minecraft:dead_tube_coral": "Dead Tube Coral",
    "minecraft:dead_tube_coral_block": "Dead Tube Coral Block",
    "minecraft:dead_tube_coral_fan": "Dead Tube Coral Fan",
    "minecraft:debug_stick": "Debug Stick",
    "minecraft:decorated_pot": "Decorated Pot",
    "minecraft:deepslate": "Slate",
    "minecraft:deepslate_brick_slab": "Slate Brick Slab",
    "minecraft:deepslate_brick_stairs": "Slate Brick Stairs",
    "minecraft:deepslate_brick_wall": "Slate Brick Wall",
    "minecraft:deepslate_bricks": "Slate Bricks",
    "minecraft:deepslate_coal_ore": "Slate Coal Ore",
    "minecraft:deepslate_copper_ore": "Slate Copper Ore",
    "minecraft:deepslate_diamond_ore": "Slate Diamond Ore",
    "minecraft:deepslate_emerald_ore": "Slate Serpent Scale Ore",
    "minecraft:deepslate_gold_ore": "Slate Gold Ore",
    "minecraft:deepslate_iron_ore": "Slate Iron Ore",
    "minecraft:deepslate_lapis_ore": "Slate Lapis Lazuli Ore",
    "minecraft:deepslate_redstone_ore": "Slate Redstone Ore",
    "minecraft:deepslate_tile_slab": "Slate Tile Slab",
    "minecraft:deepslate_tile_stairs": "Slate Tile Stairs",
    "minecraft:deepslate_tile_wall": "Slate Tile Wall",
    "minecraft:deepslate_tiles": "Slate Tiles",
    "minecraft:detector_rail": "Detector Rail",
    "minecraft:diamond": "Diamond",
    "minecraft:diamond_axe": "Diamond Axe",
    "minecraft:diamond_block": "Block of Diamond",
    "minecraft:diamond_boots": "Diamond Boots",
    "minecraft:diamond_chestplate": "Diamond Chestplate",
    "minecraft:diamond_helmet": "Diamond Helmet",
    "minecraft:diamond_hoe": "Diamond Hoe",
    "minecraft:diamond_horse_armor": "Diamond Horse Armor",
    "minecraft:diamond_leggings": "Diamond Leggings",
    "minecraft:diamond_ore": "Diamond Ore",
    "minecraft:diamond_pickaxe": "Diamond Pickaxe",
    "minecraft:diamond_shovel": "Diamond Shovel",
    "minecraft:diamond_sword": "Diamond Sword",
    "minecraft:diorite": "Diorite",
    "minecraft:diorite_slab": "Diorite Slab",
    "minecraft:diorite_stairs": "Diorite Stairs",
    "minecraft:diorite_wall": "Diorite Wall",
    "minecraft:dirt": "Dirt",
    "minecraft:dirt_path": "Dirt Path",
    "minecraft:disc_fragment_5": "Disc Fragment",
    "minecraft:dispenser": "Dispenser",
    "minecraft:dolphin_spawn_egg": "Zenith",
    "minecraft:donkey_spawn_egg": "Avsohm'Kohl",
    "minecraft:dragon_breath": "Dragon's Breath",
    "minecraft:dragon_egg": "Fear's Husk",
    "minecraft:dragon_head": "Head of Tethlaen",
    "minecraft:dried_kelp": "Dried Kelp",
    "minecraft:dried_kelp_block": "Dried Kelp Block",
    "minecraft:dripstone_block": "Dripstone Block",
    "minecraft:dropper": "Dropper",
    "minecraft:drowned_spawn_egg": "Drowned Spawn Egg",
    "minecraft:dune_armor_trim_smithing_template": "Smithing Template",
    "minecraft:echo_shard": "Echo Shard",
    "minecraft:egg": "Egg",
    "minecraft:elder_guardian_spawn_egg": "Elder Dahrkin Spawn Egg",
    "minecraft:elytra": "Glider",
    "minecraft:emerald": "Scale",
    "minecraft:emerald_block": "Block of Serpent Scales",
    "minecraft:emerald_ore": "Serpent Scale Ore",
    "minecraft:enchanted_book": "Runic Book",
    "minecraft:enchanted_golden_apple": "Fruit of the Primal Tree",
    "minecraft:enchanting_table": "Runic Inscription Table",
    "minecraft:end_crystal": "Unstable Primal Catalyst",
    "minecraft:end_portal_frame": "Anomaly Inhibitor",
    "minecraft:end_rod": "Light Rod",
    "minecraft:end_stone": "Otherstone",
    "minecraft:end_stone_brick_slab": "Otherstone Brick Slab",
    "minecraft:end_stone_brick_stairs": "Otherstone Brick Stairs",
    "minecraft:end_stone_brick_wall": "Otherstone Brick Wall",
    "minecraft:end_stone_bricks": "Otherstone Bricks",
    "minecraft:ender_chest": "Primal Cache",
    "minecraft:ender_dragon_spawn_egg": "Ender Dragon Spawn Egg",
    "minecraft:ender_eye": "Oculus of Nothing",
    "minecraft:ender_pearl": "Primal Pearl",
    "minecraft:enderman_spawn_egg": "Penumbra",
    "minecraft:endermite_spawn_egg": "Osteogenesis",
    "minecraft:evoker_spawn_egg": "Thundercrux",
    "minecraft:experience_bottle": "Arcane Bottle",
    "minecraft:explorer_pottery_sherd": "Explorer Pottery Sherd",
    "minecraft:exposed_copper": "Exposed Copper",
    "minecraft:exposed_cut_copper": "Exposed Cut Copper",
    "minecraft:exposed_cut_copper_slab": "Exposed Cut Copper Slab",
    "minecraft:exposed_cut_copper_stairs": "Exposed Cut Copper Stairs",
    "minecraft:eye_armor_trim_smithing_template": "Smithing Template",
    "minecraft:farmland": "Farmland",
    "minecraft:feather": "Feather",
    "minecraft:fermented_spider_eye": "Fermented Spider Eye",
    "minecraft:fern": "Fern",
    "minecraft:filled_map": "Map",
    "minecraft:fire_charge": "Fire Charge",
    "minecraft:fire_coral": "Fire Coral",
    "minecraft:fire_coral_block": "Fire Coral Block",
    "minecraft:fire_coral_fan": "Fire Coral Fan",
    "minecraft:firework_rocket": "Firework Rocket",
    "minecraft:firework_star": "Firework Star",
    "minecraft:fishing_rod": "Fishing Rod",
    "minecraft:fletching_table": "Fletching Table",
    "minecraft:flint": "Flint",
    "minecraft:flint_and_steel": "Flint and Steel",
    "minecraft:flower_banner_pattern": "Banner Pattern",
    "minecraft:flower_pot": "Flower Pot",
    "minecraft:flowering_azalea": "Flowering Azalea",
    "minecraft:flowering_azalea_leaves": "Flowering Azalea Leaves",
    "minecraft:fox_spawn_egg": "Stasis Bolt",
    "minecraft:friend_pottery_sherd": "Friend Pottery Sherd",
    "minecraft:frog_spawn_egg": "Frog Spawn Egg",
    "minecraft:frogspawn": "Frogspawn",
    "minecraft:furnace": "Furnace",
    "minecraft:furnace_minecart": "Minecart with Furnace",
    "minecraft:ghast_spawn_egg": "Pure Corruption",
    "minecraft:ghast_tear": "Quicksilver Tear",
    "minecraft:gilded_blackstone": "Gilded Blackstone",
    "minecraft:glass": "Glass",
    "minecraft:glass_bottle": "Glass Bottle",
    "minecraft:glass_pane": "Glass Pane",
    "minecraft:glistering_melon_slice": "Glistering Melon Slice",
    "minecraft:globe_banner_pattern": "Banner Pattern",
    "minecraft:glow_berries": "Glow Berries",
    "minecraft:glow_ink_sac": "Glow Ink Sac",
    "minecraft:glow_item_frame": "Glow Item Frame",
    "minecraft:glow_lichen": "Glow Lichen",
    "minecraft:glow_squid_spawn_egg": "Eyebiter",
    "minecraft:glowstone": "Glowstone",
    "minecraft:glowstone_dust": "Glowstone Dust",
    "minecraft:goat_horn": "Goat Horn",
    "minecraft:goat_spawn_egg": "WarpHorse Armor MkIII",
    "minecraft:gold_block": "Block of Gold",
    "minecraft:gold_ingot": "Gold Ingot",
    "minecraft:gold_nugget": "Gold Nugget",
    "minecraft:gold_ore": "Gold Ore",
    "minecraft:golden_apple": "Golden Apple",
    "minecraft:golden_axe": "Golden Axe",
    "minecraft:golden_boots": "Golden Boots",
    "minecraft:golden_carrot": "Golden Carrot",
    "minecraft:golden_chestplate": "Golden Chestplate",
    "minecraft:golden_helmet": "Golden Helmet",
    "minecraft:golden_hoe": "Golden Hoe",
    "minecraft:golden_horse_armor": "Golden Horse Armor",
    "minecraft:golden_leggings": "Golden Leggings",
    "minecraft:golden_pickaxe": "Golden Pickaxe",
    "minecraft:golden_shovel": "Golden Shovel",
    "minecraft:golden_sword": "Golden Sword",
    "minecraft:granite": "Granite",
    "minecraft:granite_slab": "Granite Slab",
    "minecraft:granite_stairs": "Granite Stairs",
    "minecraft:granite_wall": "Granite Wall",
    "minecraft:grass": "Grass",
    "minecraft:grass_block": "Grass Block",
    "minecraft:gravel": "Gravel",
    "minecraft:gray_banner": "Gray Banner",
    "minecraft:gray_bed": "Gray Bed",
    "minecraft:gray_candle": "Gray Candle",
    "minecraft:gray_carpet": "Gray Carpet",
    "minecraft:gray_concrete": "Gray Concrete",
    "minecraft:gray_concrete_powder": "Gray Concrete Powder",
    "minecraft:gray_dye": "Gray Dye",
    "minecraft:gray_glazed_terracotta": "Gray Glazed Terracotta",
    "minecraft:gray_shulker_box": "Gray Runic Vessel",
    "minecraft:gray_stained_glass": "Gray Stained Glass",
    "minecraft:gray_stained_glass_pane": "Gray Stained Glass Pane",
    "minecraft:gray_terracotta": "Gray Terracotta",
    "minecraft:gray_wool": "Gray Wool",
    "minecraft:green_banner": "Green Banner",
    "minecraft:green_bed": "Green Bed",
    "minecraft:green_candle": "Green Candle",
    "minecraft:green_carpet": "Green Carpet",
    "minecraft:green_concrete": "Green Concrete",
    "minecraft:green_concrete_powder": "Green Concrete Powder",
    "minecraft:green_dye": "Green Dye",
    "minecraft:green_glazed_terracotta": "Green Glazed Terracotta",
    "minecraft:green_shulker_box": "Green Runic Vessel",
    "minecraft:green_stained_glass": "Green Stained Glass",
    "minecraft:green_stained_glass_pane": "Green Stained Glass Pane",
    "minecraft:green_terracotta": "Green Terracotta",
    "minecraft:green_wool": "Green Wool",
    "minecraft:grindstone": "Grindstone",
    "minecraft:guardian_spawn_egg": "Proxigea",
    "minecraft:gunpowder": "Gunpowder",
    "minecraft:hanging_roots": "Hanging Roots",
    "minecraft:hay_block": "Hay Bale",
    "minecraft:heart_of_the_sea": "Moonstone",
    "minecraft:heart_pottery_sherd": "Heart Pottery Sherd",
    "minecraft:heartbreak_pottery_sherd": "Heartbreak Pottery Sherd",
    "minecraft:heavy_weighted_pressure_plate": "Heavy Weighted Pressure Plate",
    "minecraft:hoglin_spawn_egg": "Swinebreed Spawn Egg",
    "minecraft:honey_block": "Honey Block",
    "minecraft:honey_bottle": "Honey Bottle",
    "minecraft:honeycomb": "Honeycomb",
    "minecraft:honeycomb_block": "Honeycomb Block",
    "minecraft:hopper": "Hopper",
    "minecraft:hopper_minecart": "Minecart with Hopper",
    "minecraft:horn_coral": "Horn Coral",
    "minecraft:horn_coral_block": "Horn Coral Block",
    "minecraft:horn_coral_fan": "Horn Coral Fan",
    "minecraft:horse_spawn_egg": "Rehntite Plate Mail",
    "minecraft:host_armor_trim_smithing_template": "Smithing Template",
    "minecraft:howl_pottery_sherd": "Howl Pottery Sherd",
    "minecraft:husk_spawn_egg": "Husk Spawn Egg",
    "minecraft:ice": "Ice",
    "minecraft:infested_chiseled_stone_bricks": "Infested Chiseled Stone Bricks",
    "minecraft:infested_cobblestone": "Infested Cobblestone",
    "minecraft:infested_cracked_stone_bricks": "Infested Cracked Stone Bricks",
    "minecraft:infested_deepslate": "Infested Slate",
    "minecraft:infested_mossy_stone_bricks": "Infested Mossy Stone Bricks",
    "minecraft:infested_stone": "Infested Stone",
    "minecraft:infested_stone_bricks": "Infested Stone Bricks",
    "minecraft:ink_sac": "Ink Sac",
    "minecraft:iron_axe": "Iron Axe",
    "minecraft:iron_bars": "Iron Bars",
    "minecraft:iron_block": "Block of Iron",
    "minecraft:iron_boots": "Iron Boots",
    "minecraft:iron_chestplate": "Iron Chestplate",
    "minecraft:iron_door": "Iron Door",
    "minecraft:iron_golem_spawn_egg": "Iron Golem Spawn Egg",
    "minecraft:iron_helmet": "Iron Helmet",
    "minecraft:iron_hoe": "Iron Hoe",
    "minecraft:iron_horse_armor": "Iron Horse Armor",
    "minecraft:iron_ingot": "Iron Ingot",
    "minecraft:iron_leggings": "Iron Leggings",
    "minecraft:iron_nugget": "Iron Nugget",
    "minecraft:iron_ore": "Iron Ore",
    "minecraft:iron_pickaxe": "Iron Pickaxe",
    "minecraft:iron_shovel": "Iron Shovel",
    "minecraft:iron_sword": "Iron Sword",
    "minecraft:iron_trapdoor": "Iron Trapdoor",
    "minecraft:item_frame": "Item Frame",
    "minecraft:jack_o_lantern": "Jack o'Lantern",
    "minecraft:jigsaw": "Jiggy Block",
    "minecraft:jukebox": "Jukebox",
    "minecraft:jungle_boat": "Jungle Boat",
    "minecraft:jungle_button": "Jungle Button",
    "minecraft:jungle_chest_boat": "Jungle Boat with Chest",
    "minecraft:jungle_door": "Jungle Door",
    "minecraft:jungle_fence": "Jungle Fence",
    "minecraft:jungle_fence_gate": "Jungle Fence Gate",
    "minecraft:jungle_hanging_sign": "Jungle Hanging Sign",
    "minecraft:jungle_leaves": "Jungle Leaves",
    "minecraft:jungle_log": "Jungle Log",
    "minecraft:jungle_planks": "Jungle Planks",
    "minecraft:jungle_pressure_plate": "Jungle Pressure Plate",
    "minecraft:jungle_sapling": "Jungle Sapling",
    "minecraft:jungle_sign": "Jungle Sign",
    "minecraft:jungle_slab": "Jungle Slab",
    "minecraft:jungle_stairs": "Jungle Stairs",
    "minecraft:jungle_trapdoor": "Jungle Trapdoor",
    "minecraft:jungle_wood": "Jungle Wood",
    "minecraft:kelp": "Kelp",
    "minecraft:knowledge_book": "Knowledge Book",
    "minecraft:ladder": "Ladder",
    "minecraft:lantern": "Lantern",
    "minecraft:lapis_block": "Block of Lapis Lazuli",
    "minecraft:lapis_lazuli": "Lapis Lazuli",
    "minecraft:lapis_ore": "Lapis Lazuli Ore",
    "minecraft:large_amethyst_bud": "Large Amethyst Bud",
    "minecraft:large_fern": "Large Fern",
    "minecraft:lava_bucket": "Lava Bucket",
    "minecraft:lead": "Lead",
    "minecraft:leather": "Leather",
    "minecraft:leather_boots": "Leather Boots",
    "minecraft:leather_chestplate": "Leather Tunic",
    "minecraft:leather_helmet": "Leather Cap",
    "minecraft:leather_horse_armor": "Leather Horse Armor",
    "minecraft:leather_leggings": "Leather Pants",
    "minecraft:lectern": "Lectern",
    "minecraft:lever": "Lever",
    "minecraft:light": "Light",
    "minecraft:light_blue_banner": "Light Blue Banner",
    "minecraft:light_blue_bed": "Light Blue Bed",
    "minecraft:light_blue_candle": "Light Blue Candle",
    "minecraft:light_blue_carpet": "Light Blue Carpet",
    "minecraft:light_blue_concrete": "Light Blue Concrete",
    "minecraft:light_blue_concrete_powder": "Light Blue Concrete Powder",
    "minecraft:light_blue_dye": "Light Blue Dye",
    "minecraft:light_blue_glazed_terracotta": "Light Blue Glazed Terracotta",
    "minecraft:light_blue_shulker_box": "Light Blue Runic Vessel",
    "minecraft:light_blue_stained_glass": "Light Blue Stained Glass",
    "minecraft:light_blue_stained_glass_pane": "Light Blue Stained Glass Pane",
    "minecraft:light_blue_terracotta": "Light Blue Terracotta",
    "minecraft:light_blue_wool": "Light Blue Wool",
    "minecraft:light_gray_banner": "Light Gray Banner",
    "minecraft:light_gray_bed": "Light Gray Bed",
    "minecraft:light_gray_candle": "Light Gray Candle",
    "minecraft:light_gray_carpet": "Light Gray Carpet",
    "minecraft:light_gray_concrete": "Light Gray Concrete",
    "minecraft:light_gray_concrete_powder": "Light Gray Concrete Powder",
    "minecraft:light_gray_dye": "Light Gray Dye",
    "minecraft:light_gray_glazed_terracotta": "Light Gray Glazed Terracotta",
    "minecraft:light_gray_shulker_box": "Light Gray Runic Vessel",
    "minecraft:light_gray_stained_glass": "Light Gray Stained Glass",
    "minecraft:light_gray_stained_glass_pane": "Light Gray Stained Glass Pane",
    "minecraft:light_gray_terracotta": "Light Gray Terracotta",
    "minecraft:light_gray_wool": "Light Gray Wool",
    "minecraft:light_weighted_pressure_plate": "Light Weighted Pressure Plate",
    "minecraft:lightning_rod": "Lightning Rod",
    "minecraft:lilac": "Lilac",
    "minecraft:lily_of_the_valley": "Lily of the Valley",
    "minecraft:lily_pad": "Lily Pad",
    "minecraft:lime_banner": "Lime Banner",
    "minecraft:lime_bed": "Lime Bed",
    "minecraft:lime_candle": "Lime Candle",
    "minecraft:lime_carpet": "Lime Carpet",
    "minecraft:lime_concrete": "Lime Concrete",
    "minecraft:lime_concrete_powder": "Lime Concrete Powder",
    "minecraft:lime_dye": "Lime Dye",
    "minecraft:lime_glazed_terracotta": "Lime Glazed Terracotta",
    "minecraft:lime_shulker_box": "Lime Runic Vessel",
    "minecraft:lime_stained_glass": "Lime Stained Glass",
    "minecraft:lime_stained_glass_pane": "Lime Stained Glass Pane",
    "minecraft:lime_terracotta": "Lime Terracotta",
    "minecraft:lime_wool": "Lime Wool",
    "minecraft:lingering_potion": "Lingering Uncraftable Potion",
    "minecraft:llama_spawn_egg": "Ascendance",
    "minecraft:lodestone": "Lodestone",
    "minecraft:loom": "Loom",
    "minecraft:magenta_banner": "Magenta Banner",
    "minecraft:magenta_bed": "Magenta Bed",
    "minecraft:magenta_candle": "Magenta Candle",
    "minecraft:magenta_carpet": "Magenta Carpet",
    "minecraft:magenta_concrete": "Magenta Concrete",
    "minecraft:magenta_concrete_powder": "Magenta Concrete Powder",
    "minecraft:magenta_dye": "Magenta Dye",
    "minecraft:magenta_glazed_terracotta": "Magenta Glazed Terracotta",
    "minecraft:magenta_shulker_box": "Magenta Runic Vessel",
    "minecraft:magenta_stained_glass": "Magenta Stained Glass",
    "minecraft:magenta_stained_glass_pane": "Magenta Stained Glass Pane",
    "minecraft:magenta_terracotta": "Magenta Terracotta",
    "minecraft:magenta_wool": "Magenta Wool",
    "minecraft:magma_block": "Magma Block",
    "minecraft:magma_cream": "Magma Cream",
    "minecraft:magma_cube_spawn_egg": "The Mythbreaker",
    "minecraft:mangrove_boat": "Mangrove Boat",
    "minecraft:mangrove_button": "Mangrove Button",
    "minecraft:mangrove_chest_boat": "Mangrove Boat with Chest",
    "minecraft:mangrove_door": "Mangrove Door",
    "minecraft:mangrove_fence": "Mangrove Fence",
    "minecraft:mangrove_fence_gate": "Mangrove Fence Gate",
    "minecraft:mangrove_hanging_sign": "Mangrove Hanging Sign",
    "minecraft:mangrove_leaves": "Mangrove Leaves",
    "minecraft:mangrove_log": "Mangrove Log",
    "minecraft:mangrove_planks": "Mangrove Planks",
    "minecraft:mangrove_pressure_plate": "Mangrove Pressure Plate",
    "minecraft:mangrove_propagule": "Mangrove Propagule",
    "minecraft:mangrove_roots": "Mangrove Roots",
    "minecraft:mangrove_sign": "Mangrove Sign",
    "minecraft:mangrove_slab": "Mangrove Slab",
    "minecraft:mangrove_stairs": "Mangrove Stairs",
    "minecraft:mangrove_trapdoor": "Mangrove Trapdoor",
    "minecraft:mangrove_wood": "Mangrove Wood",
    "minecraft:map": "Empty Map",
    "minecraft:medium_amethyst_bud": "Medium Amethyst Bud",
    "minecraft:melon": "Melon",
    "minecraft:melon_seeds": "Melon Seeds",
    "minecraft:melon_slice": "Melon Slice",
    "minecraft:milk_bucket": "Milk Bucket",
    "minecraft:minecart": "Minecart",
    "minecraft:miner_pottery_sherd": "Miner Pottery Sherd",
    "minecraft:mojang_banner_pattern": "Banner Pattern",
    "minecraft:mooshroom_spawn_egg": "Mooshroom Spawn Egg",
    "minecraft:moss_block": "Moss Block",
    "minecraft:moss_carpet": "Moss Carpet",
    "minecraft:mossy_cobblestone": "Mossy Cobblestone",
    "minecraft:mossy_cobblestone_slab": "Mossy Cobblestone Slab",
    "minecraft:mossy_cobblestone_stairs": "Mossy Cobblestone Stairs",
    "minecraft:mossy_cobblestone_wall": "Mossy Cobblestone Wall",
    "minecraft:mossy_stone_brick_slab": "Mossy Stone Brick Slab",
    "minecraft:mossy_stone_brick_stairs": "Mossy Stone Brick Stairs",
    "minecraft:mossy_stone_brick_wall": "Mossy Stone Brick Wall",
    "minecraft:mossy_stone_bricks": "Mossy Stone Bricks",
    "minecraft:mourner_pottery_sherd": "Mourner Pottery Sherd",
    "minecraft:mud": "Mud",
    "minecraft:mud_brick_slab": "Mud Brick Slab",
    "minecraft:mud_brick_stairs": "Mud Brick Stairs",
    "minecraft:mud_brick_wall": "Mud Brick Wall",
    "minecraft:mud_bricks": "Mud Bricks",
    "minecraft:muddy_mangrove_roots": "Muddy Mangrove Roots",
    "minecraft:mule_spawn_egg": "Mule Spawn Egg",
    "minecraft:mushroom_stem": "Mushroom Stem",
    "minecraft:mushroom_stew": "Mushroom Stew",
    "minecraft:music_disc_11": "Music Disc",
    "minecraft:music_disc_13": "Music Disc",
    "minecraft:music_disc_5": "Music Disc",
    "minecraft:music_disc_blocks": "Music Disc",
    "minecraft:music_disc_cat": "Music Disc",
    "minecraft:music_disc_chirp": "Music Disc",
    "minecraft:music_disc_far": "Music Disc",
    "minecraft:music_disc_mall": "Music Disc",
    "minecraft:music_disc_mellohi": "Music Disc",
    "minecraft:music_disc_otherside": "Music Disc",
    "minecraft:music_disc_pigstep": "Music Disc",
    "minecraft:music_disc_relic": "Music Disc",
    "minecraft:music_disc_stal": "Music Disc",
    "minecraft:music_disc_strad": "Music Disc",
    "minecraft:music_disc_wait": "Music Disc",
    "minecraft:music_disc_ward": "Music Disc",
    "minecraft:mutton": "Raw Mutton",
    "minecraft:mycelium": "Mycelium",
    "minecraft:name_tag": "Name Tag",
    "minecraft:nautilus_shell": "Nautilus Shell",
    "minecraft:nether_brick": "Taihryte Brick",
    "minecraft:nether_brick_fence": "Taihryte Brick Fence",
    "minecraft:nether_brick_slab": "Taihryte Brick Slab",
    "minecraft:nether_brick_stairs": "Taihryte Brick Stairs",
    "minecraft:nether_brick_wall": "Taihryte Brick Wall",
    "minecraft:nether_bricks": "Taihryte Bricks",
    "minecraft:nether_gold_ore": "Slate Gold Ore",
    "minecraft:nether_quartz_ore": "Slate Quartz Ore",
    "minecraft:nether_sprouts": "Aventurine Sprouts",
    "minecraft:nether_star": "Soul Asteria",
    "minecraft:nether_wart": "Crucible Wart",
    "minecraft:nether_wart_block": "Crucible Wart Block",
    "minecraft:netherite_axe": "Celestial Axe",
    "minecraft:netherite_block": "Block of Celestial Alloy",
    "minecraft:netherite_boots": "Celestial Boots",
    "minecraft:netherite_chestplate": "Celestial Chestplate",
    "minecraft:netherite_helmet": "Celestial Helmet",
    "minecraft:netherite_hoe": "Celestial Hoe",
    "minecraft:netherite_ingot": "Celestial Alloy",
    "minecraft:netherite_leggings": "Celestial Leggings",
    "minecraft:netherite_pickaxe": "Celestial Pickaxe",
    "minecraft:netherite_scrap": "Celestial Chondrule",
    "minecraft:netherite_shovel": "Celestial Shovel",
    "minecraft:netherite_sword": "Celestial Sword",
    "minecraft:netherite_upgrade_smithing_template": "Smithing Template",
    "minecraft:netherrack": "Taihryte",
    "minecraft:note_block": "Note Block",
    "minecraft:oak_boat": "Oak Boat",
    "minecraft:oak_button": "Oak Button",
    "minecraft:oak_chest_boat": "Oak Boat with Chest",
    "minecraft:oak_door": "Oak Door",
    "minecraft:oak_fence": "Oak Fence",
    "minecraft:oak_fence_gate": "Oak Fence Gate",
    "minecraft:oak_hanging_sign": "Oak Hanging Sign",
    "minecraft:oak_leaves": "Oak Leaves",
    "minecraft:oak_log": "Oak Log",
    "minecraft:oak_planks": "Oak Planks",
    "minecraft:oak_pressure_plate": "Oak Pressure Plate",
    "minecraft:oak_sapling": "Oak Sapling",
    "minecraft:oak_sign": "Oak Sign",
    "minecraft:oak_slab": "Oak Slab",
    "minecraft:oak_stairs": "Oak Stairs",
    "minecraft:oak_trapdoor": "Oak Trapdoor",
    "minecraft:oak_wood": "Oak Wood",
    "minecraft:observer": "Observer",
    "minecraft:obsidian": "Obsidian",
    "minecraft:ocelot_spawn_egg": "Frenzy",
    "minecraft:ochre_froglight": "Ochre Froglight",
    "minecraft:orange_banner": "Orange Banner",
    "minecraft:orange_bed": "Orange Bed",
    "minecraft:orange_candle": "Orange Candle",
    "minecraft:orange_carpet": "Orange Carpet",
    "minecraft:orange_concrete": "Orange Concrete",
    "minecraft:orange_concrete_powder": "Orange Concrete Powder",
    "minecraft:orange_dye": "Orange Dye",
    "minecraft:orange_glazed_terracotta": "Orange Glazed Terracotta",
    "minecraft:orange_shulker_box": "Orange Runic Vessel",
    "minecraft:orange_stained_glass": "Orange Stained Glass",
    "minecraft:orange_stained_glass_pane": "Orange Stained Glass Pane",
    "minecraft:orange_terracotta": "Orange Terracotta",
    "minecraft:orange_tulip": "Orange Tulip",
    "minecraft:orange_wool": "Orange Wool",
    "minecraft:oxeye_daisy": "Oxeye Daisy",
    "minecraft:oxidized_copper": "Oxidized Copper",
    "minecraft:oxidized_cut_copper": "Oxidized Cut Copper",
    "minecraft:oxidized_cut_copper_slab": "Oxidized Cut Copper Slab",
    "minecraft:oxidized_cut_copper_stairs": "Oxidized Cut Copper Stairs",
    "minecraft:packed_ice": "Packed Ice",
    "minecraft:packed_mud": "Packed Mud",
    "minecraft:painting": "Painting",
    "minecraft:panda_spawn_egg": "Tul'Vohaln",
    "minecraft:paper": "Paper",
    "minecraft:parrot_spawn_egg": "One Thousand Scars",
    "minecraft:pearlescent_froglight": "Pearlescent Froglight",
    "minecraft:peony": "Peony",
    "minecraft:petrified_oak_slab": "Petrified Oak Slab",
    "minecraft:phantom_membrane": "Ruin Membrane",
    "minecraft:phantom_spawn_egg": "Whispersong",
    "minecraft:pig_spawn_egg": "Malevolentia",
    "minecraft:piglin_banner_pattern": "Banner Pattern",
    "minecraft:piglin_brute_spawn_egg": "Maelmari Brute Spawn Egg",
    "minecraft:piglin_head": "Piglin Head",
    "minecraft:piglin_spawn_egg": "Maelmari Spawn Egg",
    "minecraft:pillager_spawn_egg": "Mihkmari Spawn Egg",
    "minecraft:pink_banner": "Pink Banner",
    "minecraft:pink_bed": "Pink Bed",
    "minecraft:pink_candle": "Pink Candle",
    "minecraft:pink_carpet": "Pink Carpet",
    "minecraft:pink_concrete": "Pink Concrete",
    "minecraft:pink_concrete_powder": "Pink Concrete Powder",
    "minecraft:pink_dye": "Pink Dye",
    "minecraft:pink_glazed_terracotta": "Pink Glazed Terracotta",
    "minecraft:pink_petals": "Pink Petals",
    "minecraft:pink_shulker_box": "Pink Runic Vessel",
    "minecraft:pink_stained_glass": "Pink Stained Glass",
    "minecraft:pink_stained_glass_pane": "Pink Stained Glass Pane",
    "minecraft:pink_terracotta": "Pink Terracotta",
    "minecraft:pink_tulip": "Pink Tulip",
    "minecraft:pink_wool": "Pink Wool",
    "minecraft:piston": "Piston",
    "minecraft:pitcher_plant": "Pitcher Plant",
    "minecraft:pitcher_pod": "Pitcher Pod",
    "minecraft:player_head": "Player Head",
    "minecraft:plenty_pottery_sherd": "Plenty Pottery Sherd",
    "minecraft:podzol": "Podzol",
    "minecraft:pointed_dripstone": "Pointed Dripstone",
    "minecraft:poisonous_potato": "Poisonous Potato",
    "minecraft:polar_bear_spawn_egg": "Polar Bear Spawn Egg",
    "minecraft:polished_andesite": "Polished Andesite",
    "minecraft:polished_andesite_slab": "Polished Andesite Slab",
    "minecraft:polished_andesite_stairs": "Polished Andesite Stairs",
    "minecraft:polished_basalt": "Polished Basalt",
    "minecraft:polished_blackstone": "Polished Blackstone",
    "minecraft:polished_blackstone_brick_slab": "Polished Blackstone Brick Slab",
    "minecraft:polished_blackstone_brick_stairs": "Polished Blackstone Brick Stairs",
    "minecraft:polished_blackstone_brick_wall": "Polished Blackstone Brick Wall",
    "minecraft:polished_blackstone_bricks": "Polished Blackstone Bricks",
    "minecraft:polished_blackstone_button": "Polished Blackstone Button",
    "minecraft:polished_blackstone_pressure_plate": "Polished Blackstone Pressure Plate",
    "minecraft:polished_blackstone_slab": "Polished Blackstone Slab",
    "minecraft:polished_blackstone_stairs": "Polished Blackstone Stairs",
    "minecraft:polished_blackstone_wall": "Polished Blackstone Wall",
    "minecraft:polished_deepslate": "Polished Slate",
    "minecraft:polished_deepslate_slab": "Polished Slate Slab",
    "minecraft:polished_deepslate_stairs": "Polished Slate Stairs",
    "minecraft:polished_deepslate_wall": "Polished Slate Wall",
    "minecraft:polished_diorite": "Polished Diorite",
    "minecraft:polished_diorite_slab": "Polished Diorite Slab",
    "minecraft:polished_diorite_stairs": "Polished Diorite Stairs",
    "minecraft:polished_granite": "Polished Granite",
    "minecraft:polished_granite_slab": "Polished Granite Slab",
    "minecraft:polished_granite_stairs": "Polished Granite Stairs",
    "minecraft:popped_chorus_fruit": "Popped Chorus Fruit",
    "minecraft:poppy": "Poppy",
    "minecraft:porkchop": "Raw Porkchop",
    "minecraft:potato": "Potato",
    "minecraft:potion": "Uncraftable Potion",
    "minecraft:powder_snow_bucket": "Powder Snow Bucket",
    "minecraft:powered_rail": "Powered Rail",
    "minecraft:prismarine": "Prismarine",
    "minecraft:prismarine_brick_slab": "Prismarine Brick Slab",
    "minecraft:prismarine_brick_stairs": "Prismarine Brick Stairs",
    "minecraft:prismarine_bricks": "Prismarine Bricks",
    "minecraft:prismarine_crystals": "Azure Crystals",
    "minecraft:prismarine_shard": "Prismarine Shard",
    "minecraft:prismarine_slab": "Prismarine Slab",
    "minecraft:prismarine_stairs": "Prismarine Stairs",
    "minecraft:prismarine_wall": "Prismarine Wall",
    "minecraft:prize_pottery_sherd": "Prize Pottery Sherd",
    "minecraft:pufferfish": "Pufferfish",
    "minecraft:pufferfish_bucket": "Bucket of Pufferfish",
    "minecraft:pufferfish_spawn_egg": "Hovadchear's Greathammer",
    "minecraft:pumpkin": "Pumpkin",
    "minecraft:pumpkin_pie": "Pumpkin Pie",
    "minecraft:pumpkin_seeds": "Pumpkin Seeds",
    "minecraft:purple_banner": "Purple Banner",
    "minecraft:purple_bed": "Purple Bed",
    "minecraft:purple_candle": "Purple Candle",
    "minecraft:purple_carpet": "Purple Carpet",
    "minecraft:purple_concrete": "Purple Concrete",
    "minecraft:purple_concrete_powder": "Purple Concrete Powder",
    "minecraft:purple_dye": "Purple Dye",
    "minecraft:purple_glazed_terracotta": "Purple Glazed Terracotta",
    "minecraft:purple_shulker_box": "Purple Runic Vessel",
    "minecraft:purple_stained_glass": "Purple Stained Glass",
    "minecraft:purple_stained_glass_pane": "Purple Stained Glass Pane",
    "minecraft:purple_terracotta": "Purple Terracotta",
    "minecraft:purple_wool": "Purple Wool",
    "minecraft:purpur_block": "Amethyst Tile Block",
    "minecraft:purpur_pillar": "Infused Amethyst",
    "minecraft:purpur_slab": "Amethyst Tile Slab",
    "minecraft:purpur_stairs": "Amethyst Tile Stairs",
    "minecraft:quartz": "Quartz",
    "minecraft:quartz_block": "Block of Quartz",
    "minecraft:quartz_bricks": "Quartz Bricks",
    "minecraft:quartz_pillar": "Quartz Pillar",
    "minecraft:quartz_slab": "Quartz Slab",
    "minecraft:quartz_stairs": "Quartz Stairs",
    "minecraft:rabbit": "Raw Rabbit",
    "minecraft:rabbit_foot": "Rabbit's Foot",
    "minecraft:rabbit_hide": "Rabbit Hide",
    "minecraft:rabbit_spawn_egg": "Ultva's Bowblade",
    "minecraft:rabbit_stew": "Rabbit Stew",
    "minecraft:rail": "Rail",
    "minecraft:raiser_armor_trim_smithing_template": "Smithing Template",
    "minecraft:ravager_spawn_egg": "AvPod",
    "minecraft:raw_copper": "Raw Copper",
    "minecraft:raw_copper_block": "Block of Raw Copper",
    "minecraft:raw_gold": "Raw Gold",
    "minecraft:raw_gold_block": "Block of Raw Gold",
    "minecraft:raw_iron": "Raw Iron",
    "minecraft:raw_iron_block": "Block of Raw Iron",
    "minecraft:recovery_compass": "Recovery Compass",
    "minecraft:red_banner": "Red Banner",
    "minecraft:red_bed": "Red Bed",
    "minecraft:red_candle": "Red Candle",
    "minecraft:red_carpet": "Red Carpet",
    "minecraft:red_concrete": "Red Concrete",
    "minecraft:red_concrete_powder": "Red Concrete Powder",
    "minecraft:red_dye": "Red Dye",
    "minecraft:red_glazed_terracotta": "Red Glazed Terracotta",
    "minecraft:red_mushroom": "Red Mushroom",
    "minecraft:red_mushroom_block": "Red Mushroom Block",
    "minecraft:red_nether_brick_slab": "Red Taihryte Brick Slab",
    "minecraft:red_nether_brick_stairs": "Red Taihryte Brick Stairs",
    "minecraft:red_nether_brick_wall": "Red Taihryte Brick Wall",
    "minecraft:red_nether_bricks": "Red Taihryte Bricks",
    "minecraft:red_sand": "Red Sand",
    "minecraft:red_sandstone": "Red Sandstone",
    "minecraft:red_sandstone_slab": "Red Sandstone Slab",
    "minecraft:red_sandstone_stairs": "Red Sandstone Stairs",
    "minecraft:red_sandstone_wall": "Red Sandstone Wall",
    "minecraft:red_shulker_box": "Red Runic Vessel",
    "minecraft:red_stained_glass": "Red Stained Glass",
    "minecraft:red_stained_glass_pane": "Red Stained Glass Pane",
    "minecraft:red_terracotta": "Red Terracotta",
    "minecraft:red_tulip": "Red Tulip",
    "minecraft:red_wool": "Red Wool",
    "minecraft:redstone": "Redstone Dust",
    "minecraft:redstone_block": "Block of Redstone",
    "minecraft:redstone_lamp": "Redstone Lamp",
    "minecraft:redstone_ore": "Redstone Ore",
    "minecraft:redstone_torch": "Redstone Torch",
    "minecraft:reinforced_deepslate": "Reinforced Deepslate",
    "minecraft:repeater": "Redstone Repeater",
    "minecraft:repeating_command_block": "Repeating Command Block",
    "minecraft:respawn_anchor": "Spectra Charge",
    "minecraft:rib_armor_trim_smithing_template": "Smithing Template",
    "minecraft:rooted_dirt": "Rooted Dirt",
    "minecraft:rose_bush": "Rose Bush",
    "minecraft:rotten_flesh": "Rotten Flesh",
    "minecraft:saddle": "Saddle",
    "minecraft:salmon": "Raw Salmon",
    "minecraft:salmon_bucket": "Bucket of Salmon",
    "minecraft:salmon_spawn_egg": "Magestep",
    "minecraft:sand": "Sand",
    "minecraft:sandstone": "Sandstone",
    "minecraft:sandstone_slab": "Sandstone Slab",
    "minecraft:sandstone_stairs": "Sandstone Stairs",
    "minecraft:sandstone_wall": "Sandstone Wall",
    "minecraft:scaffolding": "Scaffolding",
    "minecraft:sculk": "Sculk",
    "minecraft:sculk_catalyst": "Sculk Catalyst",
    "minecraft:sculk_sensor": "Sculk Sensor",
    "minecraft:sculk_shrieker": "Sculk Shrieker",
    "minecraft:sculk_vein": "Sculk Vein",
    "minecraft:scute": "Scute",
    "minecraft:sea_lantern": "Azure Lantern",
    "minecraft:sea_pickle": "Sea Pickle",
    "minecraft:seagrass": "Seagrass",
    "minecraft:sentry_armor_trim_smithing_template": "Smithing Template",
    "minecraft:shaper_armor_trim_smithing_template": "Smithing Template",
    "minecraft:sheaf_pottery_sherd": "Sheaf Pottery Sherd",
    "minecraft:shears": "Shears",
    "minecraft:sheep_spawn_egg": "Oblivion",
    "minecraft:shelter_pottery_sherd": "Shelter Pottery Sherd",
    "minecraft:shield": "Shield",
    "minecraft:shroomlight": "Flarepod",
    "minecraft:shulker_box": "Runic Vessel",
    "minecraft:shulker_shell": "Null Shell",
    "minecraft:shulker_spawn_egg": "Shulker Spawn Egg",
    "minecraft:silence_armor_trim_smithing_template": "Smithing Template",
    "minecraft:silverfish_spawn_egg": "Voidtear Dagger",
    "minecraft:skeleton_horse_spawn_egg": "Skeleton Horse Spawn Egg",
    "minecraft:skeleton_skull": "Skeleton Skull",
    "minecraft:skeleton_spawn_egg": "Skeleton Spawn Egg",
    "minecraft:skull_banner_pattern": "Banner Pattern",
    "minecraft:skull_pottery_sherd": "Skull Pottery Sherd",
    "minecraft:slime_ball": "Slimeball",
    "minecraft:slime_block": "Slime Block",
    "minecraft:slime_spawn_egg": "Slime Spawn Egg",
    "minecraft:small_amethyst_bud": "Small Amethyst Bud",
    "minecraft:small_dripleaf": "Small Dripleaf",
    "minecraft:smithing_table": "Smithing Table",
    "minecraft:smoker": "Smoker",
    "minecraft:smooth_basalt": "Smooth Basalt",
    "minecraft:smooth_quartz": "Smooth Quartz Block",
    "minecraft:smooth_quartz_slab": "Smooth Quartz Slab",
    "minecraft:smooth_quartz_stairs": "Smooth Quartz Stairs",
    "minecraft:smooth_red_sandstone": "Smooth Red Sandstone",
    "minecraft:smooth_red_sandstone_slab": "Smooth Red Sandstone Slab",
    "minecraft:smooth_red_sandstone_stairs": "Smooth Red Sandstone Stairs",
    "minecraft:smooth_sandstone": "Smooth Sandstone",
    "minecraft:smooth_sandstone_slab": "Smooth Sandstone Slab",
    "minecraft:smooth_sandstone_stairs": "Smooth Sandstone Stairs",
    "minecraft:smooth_stone": "Smooth Stone",
    "minecraft:smooth_stone_slab": "Smooth Stone Slab",
    "minecraft:sniffer_egg": "Sniffer Egg",
    "minecraft:sniffer_spawn_egg": "Sniffer Spawn Egg",
    "minecraft:snort_pottery_sherd": "Snort Pottery Sherd",
    "minecraft:snout_armor_trim_smithing_template": "Smithing Template",
    "minecraft:snow": "Snow",
    "minecraft:snow_block": "Snow Block",
    "minecraft:snow_golem_spawn_egg": "Snow Golem Spawn Egg",
    "minecraft:snowball": "Snowball",
    "minecraft:soul_campfire": "Orderflame Campfire",
    "minecraft:soul_lantern": "Orderflame Lantern",
    "minecraft:soul_sand": "Soul Sand",
    "minecraft:soul_soil": "Souldust",
    "minecraft:soul_torch": "Orderflame Torch",
    "minecraft:spawner": "Spawner",
    "minecraft:spectral_arrow": "Truesight Arrow",
    "minecraft:spider_eye": "Spider Eye",
    "minecraft:spider_spawn_egg": "Spider Spawn Egg",
    "minecraft:spire_armor_trim_smithing_template": "Smithing Template",
    "minecraft:splash_potion": "Splash Uncraftable Potion",
    "minecraft:sponge": "Sponge",
    "minecraft:spore_blossom": "Spore Blossom",
    "minecraft:spruce_boat": "Spruce Boat",
    "minecraft:spruce_button": "Spruce Button",
    "minecraft:spruce_chest_boat": "Spruce Boat with Chest",
    "minecraft:spruce_door": "Spruce Door",
    "minecraft:spruce_fence": "Spruce Fence",
    "minecraft:spruce_fence_gate": "Spruce Fence Gate",
    "minecraft:spruce_hanging_sign": "Spruce Hanging Sign",
    "minecraft:spruce_leaves": "Spruce Leaves",
    "minecraft:spruce_log": "Spruce Log",
    "minecraft:spruce_planks": "Spruce Planks",
    "minecraft:spruce_pressure_plate": "Spruce Pressure Plate",
    "minecraft:spruce_sapling": "Spruce Sapling",
    "minecraft:spruce_sign": "Spruce Sign",
    "minecraft:spruce_slab": "Spruce Slab",
    "minecraft:spruce_stairs": "Spruce Stairs",
    "minecraft:spruce_trapdoor": "Spruce Trapdoor",
    "minecraft:spruce_wood": "Spruce Wood",
    "minecraft:spyglass": "Spyglass",
    "minecraft:squid_spawn_egg": "The Frostfang",
    "minecraft:stick": "Stick",
    "minecraft:sticky_piston": "Sticky Piston",
    "minecraft:stone": "Stone",
    "minecraft:stone_axe": "Stone Axe",
    "minecraft:stone_brick_slab": "Stone Brick Slab",
    "minecraft:stone_brick_stairs": "Stone Brick Stairs",
    "minecraft:stone_brick_wall": "Stone Brick Wall",
    "minecraft:stone_bricks": "Stone Bricks",
    "minecraft:stone_button": "Stone Button",
    "minecraft:stone_hoe": "Stone Hoe",
    "minecraft:stone_pickaxe": "Stone Pickaxe",
    "minecraft:stone_pressure_plate": "Stone Pressure Plate",
    "minecraft:stone_shovel": "Stone Shovel",
    "minecraft:stone_slab": "Stone Slab",
    "minecraft:stone_stairs": "Stone Stairs",
    "minecraft:stone_sword": "Stone Sword",
    "minecraft:stonecutter": "Stonecutter",
    "minecraft:stray_spawn_egg": "Stray Spawn Egg",
    "minecraft:strider_spawn_egg": "Laikin Spawn Egg",
    "minecraft:string": "String",
    "minecraft:stripped_acacia_log": "Stripped Acacia Log",
    "minecraft:stripped_acacia_wood": "Stripped Acacia Wood",
    "minecraft:stripped_bamboo_block": "Block of Stripped Bamboo",
    "minecraft:stripped_birch_log": "Stripped Birch Log",
    "minecraft:stripped_birch_wood": "Stripped Birch Wood",
    "minecraft:stripped_cherry_log": "Stripped Cherry Log",
    "minecraft:stripped_cherry_wood": "Stripped Cherry Wood",
    "minecraft:stripped_crimson_hyphae": "Stripped Carnelian Hyphae",
    "minecraft:stripped_crimson_stem": "Stripped Carnelian Stem",
    "minecraft:stripped_dark_oak_log": "Stripped Dark Oak Log",
    "minecraft:stripped_dark_oak_wood": "Stripped Dark Oak Wood",
    "minecraft:stripped_jungle_log": "Stripped Jungle Log",
    "minecraft:stripped_jungle_wood": "Stripped Jungle Wood",
    "minecraft:stripped_mangrove_log": "Stripped Mangrove Log",
    "minecraft:stripped_mangrove_wood": "Stripped Mangrove Wood",
    "minecraft:stripped_oak_log": "Stripped Oak Log",
    "minecraft:stripped_oak_wood": "Stripped Oak Wood",
    "minecraft:stripped_spruce_log": "Stripped Spruce Log",
    "minecraft:stripped_spruce_wood": "Stripped Spruce Wood",
    "minecraft:stripped_warped_hyphae": "Stripped Aventurine Hyphae",
    "minecraft:stripped_warped_stem": "Stripped Aventurine Stem",
    "minecraft:structure_block": "Minecraft Sex Block",
    "minecraft:structure_void": "Structure Void",
    "minecraft:sugar": "Sugar",
    "minecraft:sugar_cane": "Sugar Cane",
    "minecraft:sunflower": "Sunflower",
    "minecraft:suspicious_gravel": "Suspicious Gravel",
    "minecraft:suspicious_sand": "Suspicious Sand",
    "minecraft:suspicious_stew": "Suspicious Stew",
    "minecraft:sweet_berries": "Sweet Berries",
    "minecraft:tadpole_bucket": "Bucket of Tadpole",
    "minecraft:tadpole_spawn_egg": "Tadpole Spawn Egg",
    "minecraft:tall_grass": "Tall Grass",
    "minecraft:target": "Target",
    "minecraft:terracotta": "Terracotta",
    "minecraft:tide_armor_trim_smithing_template": "Smithing Template",
    "minecraft:tinted_glass": "Tinted Glass",
    "minecraft:tipped_arrow": "Uncraftable Tipped Arrow",
    "minecraft:tnt": "TNT",
    "minecraft:tnt_minecart": "Minecart with TNT",
    "minecraft:torch": "Torch",
    "minecraft:torchflower": "Torchflower",
    "minecraft:torchflower_seeds": "Torchflower Seeds",
    "minecraft:totem_of_undying": "Totem of Undying",
    "minecraft:trader_llama_spawn_egg": "Orchidaceae",
    "minecraft:trapped_chest": "Trapped Chest",
    "minecraft:trident": "Trident",
    "minecraft:tripwire_hook": "Tripwire Hook",
    "minecraft:tropical_fish": "Tropical Fish",
    "minecraft:tropical_fish_bucket": "Bucket of Tropical Fish",
    "minecraft:tropical_fish_spawn_egg": "Festering Strides",
    "minecraft:tube_coral": "Tube Coral",
    "minecraft:tube_coral_block": "Tube Coral Block",
    "minecraft:tube_coral_fan": "Tube Coral Fan",
    "minecraft:tuff": "Tuff",
    "minecraft:turtle_egg": "Turtle Egg",
    "minecraft:turtle_helmet": "Turtle Shell",
    "minecraft:turtle_spawn_egg": "Turtle Spawn Egg",
    "minecraft:twisting_vines": "Twisting Vines",
    "minecraft:verdant_froglight": "Verdant Froglight",
    "minecraft:vex_armor_trim_smithing_template": "Smithing Template",
    "minecraft:vex_spawn_egg": "Emperor Anyr's Scepter",
    "minecraft:villager_spawn_egg": "Villager Spawn Egg",
    "minecraft:vindicator_spawn_egg": "Mihkmari Warrior Spawn Egg",
    "minecraft:vine": "Vines",
    "minecraft:wandering_trader_spawn_egg": "Aurastaff of Permafrost",
    "minecraft:ward_armor_trim_smithing_template": "Smithing Template",
    "minecraft:warden_spawn_egg": "Warden Spawn Egg",
    "minecraft:warped_button": "Aventurine Button",
    "minecraft:warped_door": "Aventurine Door",
    "minecraft:warped_fence": "Aventurine Fence",
    "minecraft:warped_fence_gate": "Aventurine Fence Gate",
    "minecraft:warped_fungus": "Aventurine Fungus",
    "minecraft:warped_fungus_on_a_stick": "Aventurine Fungus on a Stick",
    "minecraft:warped_hanging_sign": "Aventurine Hanging Sign",
    "minecraft:warped_hyphae": "Aventurine Hyphae",
    "minecraft:warped_nylium": "Aventurine Nylium",
    "minecraft:warped_planks": "Aventurine Planks",
    "minecraft:warped_pressure_plate": "Aventurine Pressure Plate",
    "minecraft:warped_roots": "Aventurine Roots",
    "minecraft:warped_sign": "Aventurine Sign",
    "minecraft:warped_slab": "Aventurine Slab",
    "minecraft:warped_stairs": "Aventurine Stairs",
    "minecraft:warped_stem": "Aventurine Stem",
    "minecraft:warped_trapdoor": "Aventurine Trapdoor",
    "minecraft:warped_wart_block": "Aventurine Pileus Block",
    "minecraft:water_bucket": "Water Bucket",
    "minecraft:waxed_copper_block": "Waxed Block of Copper",
    "minecraft:waxed_cut_copper": "Waxed Cut Copper",
    "minecraft:waxed_cut_copper_slab": "Waxed Cut Copper Slab",
    "minecraft:waxed_cut_copper_stairs": "Waxed Cut Copper Stairs",
    "minecraft:waxed_exposed_copper": "Waxed Exposed Copper",
    "minecraft:waxed_exposed_cut_copper": "Waxed Exposed Cut Copper",
    "minecraft:waxed_exposed_cut_copper_slab": "Waxed Exposed Cut Copper Slab",
    "minecraft:waxed_exposed_cut_copper_stairs": "Waxed Exposed Cut Copper Stairs",
    "minecraft:waxed_oxidized_copper": "Waxed Oxidized Copper",
    "minecraft:waxed_oxidized_cut_copper": "Waxed Oxidized Cut Copper",
    "minecraft:waxed_oxidized_cut_copper_slab": "Waxed Oxidized Cut Copper Slab",
    "minecraft:waxed_oxidized_cut_copper_stairs": "Waxed Oxidized Cut Copper Stairs",
    "minecraft:waxed_weathered_copper": "Waxed Weathered Copper",
    "minecraft:waxed_weathered_cut_copper": "Waxed Weathered Cut Copper",
    "minecraft:waxed_weathered_cut_copper_slab": "Waxed Weathered Cut Copper Slab",
    "minecraft:waxed_weathered_cut_copper_stairs": "Waxed Weathered Cut Copper Stairs",
    "minecraft:wayfinder_armor_trim_smithing_template": "Smithing Template",
    "minecraft:weathered_copper": "Weathered Copper",
    "minecraft:weathered_cut_copper": "Weathered Cut Copper",
    "minecraft:weathered_cut_copper_slab": "Weathered Cut Copper Slab",
    "minecraft:weathered_cut_copper_stairs": "Weathered Cut Copper Stairs",
    "minecraft:weeping_vines": "Weeping Vines",
    "minecraft:wet_sponge": "Wet Sponge",
    "minecraft:wheat": "Wheat",
    "minecraft:wheat_seeds": "Wheat Seeds",
    "minecraft:white_banner": "White Banner",
    "minecraft:white_bed": "White Bed",
    "minecraft:white_candle": "White Candle",
    "minecraft:white_carpet": "White Carpet",
    "minecraft:white_concrete": "White Concrete",
    "minecraft:white_concrete_powder": "White Concrete Powder",
    "minecraft:white_dye": "White Dye",
    "minecraft:white_glazed_terracotta": "White Glazed Terracotta",
    "minecraft:white_shulker_box": "White Runic Vessel",
    "minecraft:white_stained_glass": "White Stained Glass",
    "minecraft:white_stained_glass_pane": "White Stained Glass Pane",
    "minecraft:white_terracotta": "White Terracotta",
    "minecraft:white_tulip": "White Tulip",
    "minecraft:white_wool": "White Wool",
    "minecraft:wild_armor_trim_smithing_template": "Smithing Template",
    "minecraft:witch_spawn_egg": "Aeongale",
    "minecraft:wither_rose": "Chthonic Rose",
    "minecraft:wither_skeleton_skull": "Chthonic Skeleton Skull",
    "minecraft:wither_skeleton_spawn_egg": "Chthonic Skeleton Spawn Egg",
    "minecraft:wither_spawn_egg": "Wither Spawn Egg",
    "minecraft:wolf_spawn_egg": "The Heartaxe",
    "minecraft:wooden_axe": "Wooden Axe",
    "minecraft:wooden_hoe": "Wooden Hoe",
    "minecraft:wooden_pickaxe": "Wooden Pickaxe",
    "minecraft:wooden_shovel": "Wooden Shovel",
    "minecraft:wooden_sword": "Wooden Sword",
    "minecraft:writable_book": "Book and Quill",
    "minecraft:written_book": "Written Book",
    "minecraft:yellow_banner": "Yellow Banner",
    "minecraft:yellow_bed": "Yellow Bed",
    "minecraft:yellow_candle": "Yellow Candle",
    "minecraft:yellow_carpet": "Yellow Carpet",
    "minecraft:yellow_concrete": "Yellow Concrete",
    "minecraft:yellow_concrete_powder": "Yellow Concrete Powder",
    "minecraft:yellow_dye": "Yellow Dye",
    "minecraft:yellow_glazed_terracotta": "Yellow Glazed Terracotta",
    "minecraft:yellow_shulker_box": "Yellow Runic Vessel",
    "minecraft:yellow_stained_glass": "Yellow Stained Glass",
    "minecraft:yellow_stained_glass_pane": "Yellow Stained Glass Pane",
    "minecraft:yellow_terracotta": "Yellow Terracotta",
    "minecraft:yellow_wool": "Yellow Wool",
    "minecraft:zoglin_spawn_egg": "Zwinebreed Spawn Egg",
    "minecraft:zombie_head": "Zombie Head",
    "minecraft:zombie_horse_spawn_egg": "Zombie Horse Spawn Egg",
    "minecraft:zombie_spawn_egg": "Eldermead",
    "minecraft:zombie_villager_spawn_egg": "WarpHorse Receiver MkII",
    "minecraft:zombified_piglin_spawn_egg": "Necrotic Maelmari Spawn Egg",
}


HORSE_VARIANTS = {
    0: "White",
    1: "Creamy",
    2: "Chestnut",
    3: "Brown",
    4: "Black",
    5: "Gray",
    6: "Dark Brown",
    256: "White with White Stockings and Blaze",
    257: "Creamy with White Stockings and Blaze",
    258: "Chestnut with White Stockings and Blaze",
    259: "Brown with White Stockings and Blaze",
    260: "Black with White Stockings and Blaze",
    261: "Gray with White Stockings and Blaze",
    262: "Dark Brown with White Stockings and Blaze",
    512: "White with White Field",
    513: "Creamy with White Field",
    514: "Chestnut with White Field",
    515: "Brown with White Field",
    516: "Black with White Field",
    517: "Gray with White Field",
    518: "Dark Brown with White Field",
    768: "White with White Dots",
    769: "Creamy with White Dots",
    770: "Chestnut with White Dots",
    771: "Brown with White Dots",
    772: "Black with White Dots",
    773: "Gray with White Dots",
    774: "Dark Brown with White Dots",
    1024: "White with Black Dots",
    1025: "Creamy with Black Dots",
    1026: "Chestnut with Black Dots",
    1027: "Brown with Black Dots",
    1028: "Black with Black Dots",
    1029: "Gray with Black Dots",
    1030: "Dark Brown with Black Dots",
}
