[tool.poetry]
name = "poigen"
version = "0.1.0"
description = ""
authors = ["Zottelchen <github@zottelchen.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
